/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btlShips;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author frase
 */
public class Grid extends javax.swing.JFrame {

    private String guess = "";
    private UserGuess ug = new UserGuess();
    private int count = 0;

    private String ans = "";

    public Grid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn10 = new javax.swing.JButton();
        jbtn11 = new javax.swing.JButton();
        jbtn12 = new javax.swing.JButton();
        jbtn13 = new javax.swing.JButton();
        jbtn14 = new javax.swing.JButton();
        jbtn15 = new javax.swing.JButton();
        jbtn16 = new javax.swing.JButton();
        jbtn17 = new javax.swing.JButton();
        jbtn18 = new javax.swing.JButton();
        jbtn19 = new javax.swing.JButton();
        jbtn20 = new javax.swing.JButton();
        jbtn21 = new javax.swing.JButton();
        jbtn22 = new javax.swing.JButton();
        jbtn23 = new javax.swing.JButton();
        jbtn24 = new javax.swing.JButton();
        jbtn25 = new javax.swing.JButton();
        jbtn26 = new javax.swing.JButton();
        jbtn27 = new javax.swing.JButton();
        jbtn28 = new javax.swing.JButton();
        jbtn29 = new javax.swing.JButton();
        jbtn30 = new javax.swing.JButton();
        jbtn31 = new javax.swing.JButton();
        jbtn32 = new javax.swing.JButton();
        jbtn33 = new javax.swing.JButton();
        jbtn34 = new javax.swing.JButton();
        jbtn35 = new javax.swing.JButton();
        jbtn36 = new javax.swing.JButton();
        jbtn37 = new javax.swing.JButton();
        jbtn38 = new javax.swing.JButton();
        jbtn39 = new javax.swing.JButton();
        jbtn40 = new javax.swing.JButton();
        jbtn41 = new javax.swing.JButton();
        jbtn42 = new javax.swing.JButton();
        jbtn43 = new javax.swing.JButton();
        jbtn44 = new javax.swing.JButton();
        jbtn45 = new javax.swing.JButton();
        jbtn46 = new javax.swing.JButton();
        jbtn47 = new javax.swing.JButton();
        jbtn48 = new javax.swing.JButton();
        jbtn49 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jLabel1.setText("A");

        jLabel2.setText("1");

        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn10ActionPerformed(evt);
            }
        });

        jbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn11ActionPerformed(evt);
            }
        });

        jbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn12ActionPerformed(evt);
            }
        });

        jbtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn13ActionPerformed(evt);
            }
        });

        jbtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn14ActionPerformed(evt);
            }
        });

        jbtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn15ActionPerformed(evt);
            }
        });

        jbtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn16ActionPerformed(evt);
            }
        });

        jbtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn17ActionPerformed(evt);
            }
        });

        jbtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn18ActionPerformed(evt);
            }
        });

        jbtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn19ActionPerformed(evt);
            }
        });

        jbtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn20ActionPerformed(evt);
            }
        });

        jbtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn21ActionPerformed(evt);
            }
        });

        jbtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn22ActionPerformed(evt);
            }
        });

        jbtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn23ActionPerformed(evt);
            }
        });

        jbtn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn24ActionPerformed(evt);
            }
        });

        jbtn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn25ActionPerformed(evt);
            }
        });

        jbtn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn26ActionPerformed(evt);
            }
        });

        jbtn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn27ActionPerformed(evt);
            }
        });

        jbtn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn28ActionPerformed(evt);
            }
        });

        jbtn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn29ActionPerformed(evt);
            }
        });

        jbtn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn30ActionPerformed(evt);
            }
        });

        jbtn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn31ActionPerformed(evt);
            }
        });

        jbtn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn32ActionPerformed(evt);
            }
        });

        jbtn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn33ActionPerformed(evt);
            }
        });

        jbtn34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn34ActionPerformed(evt);
            }
        });

        jbtn35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn35ActionPerformed(evt);
            }
        });

        jbtn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn36ActionPerformed(evt);
            }
        });

        jbtn37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn37ActionPerformed(evt);
            }
        });

        jbtn38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn38ActionPerformed(evt);
            }
        });

        jbtn39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn39ActionPerformed(evt);
            }
        });

        jbtn40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn40ActionPerformed(evt);
            }
        });

        jbtn41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn41ActionPerformed(evt);
            }
        });

        jbtn42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn42ActionPerformed(evt);
            }
        });

        jbtn43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn43ActionPerformed(evt);
            }
        });

        jbtn44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn44ActionPerformed(evt);
            }
        });

        jbtn45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn45ActionPerformed(evt);
            }
        });

        jbtn46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn46ActionPerformed(evt);
            }
        });

        jbtn47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn47ActionPerformed(evt);
            }
        });

        jbtn48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn48ActionPerformed(evt);
            }
        });

        jbtn49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn49ActionPerformed(evt);
            }
        });

        jLabel3.setText("2");

        jLabel4.setText("3");

        jLabel5.setText("4");

        jLabel6.setText("5");

        jLabel7.setText("6");

        jLabel8.setText("7");

        b.setText("B");

        jLabel10.setText("C");

        jLabel11.setText("D");

        jLabel12.setText("E");

        jLabel13.setText("F");

        jLabel14.setText("G");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn24, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn25, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn27, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn28, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtn29, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn30, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn31, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn32, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn33, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn34, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn35, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtn36, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn37, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn38, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn39, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn40, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn41, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn42, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtn43, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn44, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn45, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn46, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn47, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn48, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn49, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jbtn7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn8, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbtn10, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbtn11, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbtn12, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbtn13, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jbtn14, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn36, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn37, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn38, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn39, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn40, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn41, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn42, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn49, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        guess = "A1";
        if (ug.UserG(guess) == true) {
            jbtn1.disable();
            jbtn1.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn1.disable();
            jbtn1.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        guess = "A2";
        if (ug.UserG(guess) == true) {
            jbtn2.disable();
            jbtn2.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn2.disable();
            jbtn2.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        guess = "A3";
        if (ug.UserG(guess) == true) {
            jbtn3.disable();
            jbtn3.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn3.disable();
            jbtn3.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        guess = "A4";
        if (ug.UserG(guess) == true) {
            jbtn4.disable();
            jbtn4.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn4.disable();
            jbtn4.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        guess = "A5";
        if (ug.UserG(guess) == true) {
            jbtn5.disable();
            jbtn5.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn5.disable();
            jbtn5.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        guess = "A6";
        if (ug.UserG(guess) == true) {
            jbtn6.disable();
            jbtn6.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn6.disable();
            jbtn6.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        guess = "A7";
        if (ug.UserG(guess) == true) {
            jbtn7.disable();
            jbtn7.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn7.disable();
            jbtn7.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        btlShip btl = new btlShip();
        String arr[][] = btl.setShips();
        System.out.println("***********");
        for (int j = 0; j < arr.length; j++) {
            for (int i = 0; i < arr.length; i++) {
                System.out.println(arr[j][i]);
            }
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        guess = "B1";
        if (ug.UserG(guess) == true) {
            jbtn8.disable();
            jbtn8.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn8.disable();
            jbtn8.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        guess = "B2";
        if (ug.UserG(guess) == true) {
            jbtn9.disable();
            jbtn9.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn9.disable();
            jbtn9.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn10ActionPerformed
        guess = "B3";
        if (ug.UserG(guess) == true) {
            jbtn10.disable();
            jbtn10.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn10.disable();
            jbtn10.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn10ActionPerformed

    private void jbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn11ActionPerformed
        guess = "B4";
        if (ug.UserG(guess) == true) {
            jbtn11.disable();
            jbtn11.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn11.disable();
            jbtn11.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn11ActionPerformed

    private void jbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn12ActionPerformed
        guess = "B5";
        if (ug.UserG(guess) == true) {
            jbtn12.disable();
            jbtn12.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn12.disable();
            jbtn12.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn12ActionPerformed

    private void jbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn13ActionPerformed
        guess = "B6";
        if (ug.UserG(guess) == true) {
            jbtn13.disable();
            jbtn13.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn13.disable();
            jbtn13.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn13ActionPerformed

    private void jbtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn14ActionPerformed
        guess = "B7";
        if (ug.UserG(guess) == true) {
            jbtn14.disable();
            jbtn14.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn14.disable();
            jbtn14.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn14ActionPerformed

    private void jbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn15ActionPerformed
        guess = "C1";
        if (ug.UserG(guess) == true) {
            jbtn15.disable();
            jbtn15.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn15.disable();
            jbtn15.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn15ActionPerformed

    private void jbtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn16ActionPerformed
        guess = "C2";
        if (ug.UserG(guess) == true) {
            jbtn16.disable();
            jbtn16.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn16.disable();
            jbtn16.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn16ActionPerformed

    private void jbtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn17ActionPerformed
        guess = "C3";
        if (ug.UserG(guess) == true) {
            jbtn17.disable();
            jbtn17.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn17.disable();
            jbtn17.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn17ActionPerformed

    private void jbtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn18ActionPerformed
        guess = "C4";
        if (ug.UserG(guess) == true) {
            jbtn18.disable();
            jbtn18.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn18.disable();
            jbtn18.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn18ActionPerformed

    private void jbtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn19ActionPerformed
        guess = "C5";
        if (ug.UserG(guess) == true) {
            jbtn19.disable();
            jbtn19.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn19.disable();
            jbtn19.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn19ActionPerformed

    private void jbtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn20ActionPerformed
        guess = "C6";
        if (ug.UserG(guess) == true) {
            jbtn20.disable();
            jbtn20.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn20.disable();
            jbtn20.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn20ActionPerformed

    private void jbtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn21ActionPerformed
        guess = "C7";
        if (ug.UserG(guess) == true) {
            jbtn21.disable();
            jbtn21.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn21.disable();
            jbtn21.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn21ActionPerformed

    private void jbtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn22ActionPerformed
        guess = "D1";
        if (ug.UserG(guess) == true) {
            jbtn22.disable();
            jbtn22.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn22.disable();
            jbtn22.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn22ActionPerformed

    private void jbtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn23ActionPerformed
        guess = "D2";
        if (ug.UserG(guess) == true) {
            jbtn23.disable();
            jbtn23.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn23.disable();
            jbtn23.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn23ActionPerformed

    private void jbtn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn24ActionPerformed
        guess = "D3";
        if (ug.UserG(guess) == true) {
            jbtn24.disable();
            jbtn24.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn24.disable();
            jbtn24.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn24ActionPerformed

    private void jbtn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn25ActionPerformed
        guess = "D4";
        if (ug.UserG(guess) == true) {
            jbtn25.disable();
            jbtn25.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn25.disable();
            jbtn25.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn25ActionPerformed

    private void jbtn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn26ActionPerformed
        guess = "D5";
        if (ug.UserG(guess) == true) {
            jbtn26.disable();
            jbtn26.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn26.disable();
            jbtn26.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn26ActionPerformed

    private void jbtn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn27ActionPerformed
        guess = "D6";
        if (ug.UserG(guess) == true) {
            jbtn27.disable();
            jbtn27.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn27.disable();
            jbtn27.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn27ActionPerformed

    private void jbtn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn28ActionPerformed
        guess = "D7";
        if (ug.UserG(guess) == true) {
            jbtn28.disable();
            jbtn28.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn28.disable();
            jbtn28.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn28ActionPerformed

    private void jbtn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn29ActionPerformed
        guess = "E1";
        if (ug.UserG(guess) == true) {
            jbtn29.disable();
            jbtn29.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn29.disable();
            jbtn29.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn29ActionPerformed

    private void jbtn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn30ActionPerformed
        guess = "E2";
        if (ug.UserG(guess) == true) {
            jbtn30.disable();
            jbtn30.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn30.disable();
            jbtn30.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn30ActionPerformed

    private void jbtn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn31ActionPerformed
        guess = "E3";
        if (ug.UserG(guess) == true) {
            jbtn31.disable();
            jbtn31.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn31.disable();
            jbtn31.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn31ActionPerformed

    private void jbtn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn32ActionPerformed
        guess = "E4";
        if (ug.UserG(guess) == true) {
            jbtn32.disable();
            jbtn32.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn32.disable();
            jbtn32.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn32ActionPerformed

    private void jbtn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn33ActionPerformed
        guess = "E5";
        if (ug.UserG(guess) == true) {
            jbtn33.disable();
            jbtn33.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn33.disable();
            jbtn33.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn33ActionPerformed

    private void jbtn34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn34ActionPerformed
        guess = "E6";
        if (ug.UserG(guess) == true) {
            jbtn34.disable();
            jbtn34.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn34.disable();
            jbtn34.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn34ActionPerformed

    private void jbtn35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn35ActionPerformed
        guess = "E7";
        if (ug.UserG(guess) == true) {
            jbtn35.disable();
            jbtn35.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn35.disable();
            jbtn35.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn35ActionPerformed

    private void jbtn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn36ActionPerformed
        guess = "F1";
        if (ug.UserG(guess) == true) {
            jbtn36.disable();
            jbtn36.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn36.disable();
            jbtn36.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn36ActionPerformed

    private void jbtn37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn37ActionPerformed
        guess = "F2";
        if (ug.UserG(guess) == true) {
            jbtn37.disable();
            jbtn37.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn37.disable();
            jbtn37.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn37ActionPerformed

    private void jbtn38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn38ActionPerformed
        guess = "F3";
        if (ug.UserG(guess) == true) {
            jbtn38.disable();
            jbtn38.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn38.disable();
            jbtn38.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn38ActionPerformed

    private void jbtn39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn39ActionPerformed
        guess = "F4";
        if (ug.UserG(guess) == true) {
            jbtn39.disable();
            jbtn39.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn39.disable();
            jbtn39.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn39ActionPerformed

    private void jbtn40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn40ActionPerformed
        guess = "F5";
        if (ug.UserG(guess) == true) {
            jbtn40.disable();
            jbtn40.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn40.disable();
            jbtn40.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn40ActionPerformed

    private void jbtn41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn41ActionPerformed
        guess = "F6";
        if (ug.UserG(guess) == true) {
            jbtn41.disable();
            jbtn41.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn41.disable();
            jbtn41.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn41ActionPerformed

    private void jbtn42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn42ActionPerformed
        guess = "F7";
        if (ug.UserG(guess) == true) {
            jbtn42.disable();
            jbtn42.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn42.disable();
            jbtn42.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn42ActionPerformed

    private void jbtn43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn43ActionPerformed
        guess = "G1";
        if (ug.UserG(guess) == true) {
            jbtn43.disable();
            jbtn43.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn43.disable();
            jbtn43.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn43ActionPerformed

    private void jbtn44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn44ActionPerformed
        guess = "G2";
        if (ug.UserG(guess) == true) {
            jbtn44.disable();
            jbtn44.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn44.disable();
            jbtn44.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn44ActionPerformed

    private void jbtn45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn45ActionPerformed
        guess = "G3";
        if (ug.UserG(guess) == true) {
            jbtn45.disable();
            jbtn45.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn45.disable();
            jbtn45.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn45ActionPerformed

    private void jbtn46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn46ActionPerformed
        guess = "G4";
        if (ug.UserG(guess) == true) {
            jbtn46.disable();
            jbtn46.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn46.disable();
            jbtn46.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn46ActionPerformed

    private void jbtn47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn47ActionPerformed
        guess = "G5";
        if (ug.UserG(guess) == true) {
            jbtn47.disable();
            jbtn47.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn47.disable();
            jbtn47.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn47ActionPerformed

    private void jbtn48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn48ActionPerformed
        guess = "G6";
        if (ug.UserG(guess) == true) {
            jbtn48.disable();
            jbtn48.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn48.disable();
            jbtn48.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn48ActionPerformed

    private void jbtn49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn49ActionPerformed
        guess = "G7";
        if (ug.UserG(guess) == true) {
            jbtn49.disable();
            jbtn49.setBackground(Color.red);
            count++;
            GameEnd(count);
        } else {
            jbtn49.disable();
            jbtn49.setBackground(Color.blue);
        }
    }//GEN-LAST:event_jbtn49ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void GameStart(boolean flag) {
        Grid g = new Grid();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(flag == false){
                g.setVisible(true);
                }
                else{
                    g.setVisible(false);
                    g.dispose();
                }
            }
        });
    }

    public void GameEnd(int num) {
        if (num == 9) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    g.setVisible(false);
                    g.dispose();
                }
            });
            count=0;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn10;
    private javax.swing.JButton jbtn11;
    private javax.swing.JButton jbtn12;
    private javax.swing.JButton jbtn13;
    private javax.swing.JButton jbtn14;
    private javax.swing.JButton jbtn15;
    private javax.swing.JButton jbtn16;
    private javax.swing.JButton jbtn17;
    private javax.swing.JButton jbtn18;
    private javax.swing.JButton jbtn19;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn20;
    private javax.swing.JButton jbtn21;
    private javax.swing.JButton jbtn22;
    private javax.swing.JButton jbtn23;
    private javax.swing.JButton jbtn24;
    private javax.swing.JButton jbtn25;
    private javax.swing.JButton jbtn26;
    private javax.swing.JButton jbtn27;
    private javax.swing.JButton jbtn28;
    private javax.swing.JButton jbtn29;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn30;
    private javax.swing.JButton jbtn31;
    private javax.swing.JButton jbtn32;
    private javax.swing.JButton jbtn33;
    private javax.swing.JButton jbtn34;
    private javax.swing.JButton jbtn35;
    private javax.swing.JButton jbtn36;
    private javax.swing.JButton jbtn37;
    private javax.swing.JButton jbtn38;
    private javax.swing.JButton jbtn39;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn40;
    private javax.swing.JButton jbtn41;
    private javax.swing.JButton jbtn42;
    private javax.swing.JButton jbtn43;
    private javax.swing.JButton jbtn44;
    private javax.swing.JButton jbtn45;
    private javax.swing.JButton jbtn46;
    private javax.swing.JButton jbtn47;
    private javax.swing.JButton jbtn48;
    private javax.swing.JButton jbtn49;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    // End of variables declaration//GEN-END:variables
}
